name: Autograding

on: [push]

jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Inline Autograding Test
        run: |
          # Check if the output file exists
          if [ ! -f Level1.txt ]; then
              exit 1
          fi

          if grep -qE "^Hello [A-Za-z]+( [A-Za-z]+)?$" Level1.txt; then
              echo "Pass!"
          else
              echo "Fail!"
              exit 1
          fi
