name: Autograding

on: [push]

jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Inline Autograding Test
        run: |
          # Check if the output file exists
          if [ ! -f Level1.txt ]; then
              echo "Output file not found!"
              exit 1
          fi

          # Check if the output matches the expected format: "Hello <name>"
          if grep -qE "^Hello [A-Za-z]+$" Level1.txt; then
              echo "Test passed!"
          else
              echo "Test failed!"
              exit 1
          fi
